#!/bin/bash

work_time=25
pause_time=5
loop_amount=3
big_break=35

function pause_p {
    read -t 1 -n 1 key
    if [[ $key == "p" ]]; then
        print_stats $1 $2 $3 $4 $5
        echo "Timer paused. Press any key to resume."
        read -n 1
        print_stats $1 $2 $3 $4 $5
        
    fi
}

function print_stats {
    # i(cycle), ..._time, "...", min
    clear
    echo "$3"
    echo "Cycle: ${1} [$4]"
    echo "Time: ${5} [$2]"
     
}

function time_module {
    sec=0
    min=0

    print_stats $1 $2 $3 $4 $min  

    while (($sec<$2*60))
    do
        pause_p $1 $2 $3 $4 $min

        ((sec++))
        # echo "$sec"
        
        # check if a minute went by than update stats
        if [[ $sec == $(($min*60 + 60)) ]]; then
            ((min++))
            print_stats $1 $2 $3 $4 $min 
        fi
    done
}

function play_sound {
    play -n synth 3 pluck E2
}

# clear screen
clear
tput civis

while true
do
    
    for ((i=1; i<=$loop_amount; i++))
    do
        
        time_module $i $work_time "Work" $loop_amount

        if [[ $i<$loop_amount ]]; then
            dunstify -t $(($pause_time*60*1000)) "Pomodoro" "Short Break"
            time_module $i $pause_time "Pause" $loop_amount
            dunstify "Pomodoro" "Work Time"
        fi
    done

    dunstify -t $(($big_break*60*1000)) "Pomodoro" "Long Break"
    time_module 1 $big_break "Break" 1
    dunstify "Pomodoro" "Work Time" 


done

