#!/bin/bash

send_file () {

    # arguments: client_path user server connection server_path
    scp ${1} ${2}@${3}${4}:${5}

}


send_folder () {
    # arguments: client_path user server connection server_path
    scp -r ${1} ${2}@${3}${4}:${5}

}

receive_folder () {

    # arguments: user server connection server_path client_path
    scp -r ${1}@${2}${3}:${4} ${5}

}

receive_file () {

    # arguments: user server connection server_path client_path
    scp ${1}@${2}${3}:${4} ${5}
}

read_in_data () {
    
    scp_send=0

    while true; do
        read -p "Receive / Send (R/S): " rs
        case $rs in
            [Rr]* ) scp_send=0; break;;
            [Ss]* ) scp_send=1; break;;
            * ) echo "Please type 'R' or 'S'!";;
        esac
    done

    scp_file=0

    while true; do
        read -p "File / Directory (F/D): " fd
        case $fd in
            [Ff]* ) scp_file=1; break;;
            [Dd]* ) scp_file=0; break;;
            * ) echo "Please type 'F' or 'D'!";;
        esac
    done

    if [[ $scp_send -eq 0 ]] && [[ $scp_file -eq 0 ]]
    then

        printf "User: "
        read user
        printf "Server: "
        read server
        printf "Connection (LAN/WIFI): "
        read connection
        printf "Path (Server-side): "
        read server_path
        printf "Path (Client-side): "
        read client_path

        receive_folder $user $server $connection $server_path $client_path

    elif [[ $scp_send -eq 0 ]] && [[ $scp_file -eq 1 ]]
    then

        printf "User: "
        read user
        printf "Server: "
        read server
        printf "Connection (LAN/WIFI): "
        read connection
        printf "Path (Server-side): "
        read server_path
        printf "Path (Client-side): "
        read client_path

        receive_file $user $server $connection $server_path $client_path

    elif [[ $scp_send -eq 1 ]] && [[ $scp_file -eq 0 ]]
    then

        printf "User: "
        read user
        printf "Server: "
        read server
        printf "Connection (LAN/WIFI): "
        read connection
        printf "Path (Client-side): "
        read client_path
        printf "Path (Server-side): "
        read server_path

        send_folder $client_path $user $server $connection $server_path

    elif [[ $scp_send -eq 1 ]] && [[ $scp_file -eq 1 ]]
    then

        printf "User: "
        read user
        printf "Server: "
        read server
        printf "Connection (LAN/WIFI): "
        read connection
        printf "Path (Client-side): "
        read client_path
        printf "Path (Server-side): "
        read server_path

        send_file $client_path $user $server $connection $server_path

    fi


}

read_in_data
