#!/bin/bash

menu_blue () {

    options=( "Show devices"  "Connect devices" "Go back")

    selected=$(printf '%s\n' "${options[@]}" | dmenu -i)





    #example LinkBuds F8:4E:17:76:68:73
    
        


    case $selected in 
        "Show devices")

            devices_options=()
            devices_devices=($(bluetoothctl devices | grep -w Device | cut -d' ' -f3))
            devices_options+=(${devices_devices[@]})
            connected_devices=($(bluetoothctl info | grep -w Name: | cut -d' ' -f2))
            trusted_devices=($(bluetoothctl devices Trusted | grep -w Device | cut -d' ' -f3))

            for (( i=0; i<${#devices_devices[@]}; i++)); do
                echo "${devices_devices[i]}"
                if bluetoothctl info | grep -w Name | grep ${devices_devices[i]}; then
                    devices_options[i]+=" (Connected)"
                fi
                if bluetoothctl devices Trusted | grep -w Device | grep ${devices_devices[i]}; then
                    devices_options[i]+=" (Trusted)"
                fi
            done

            devices_options+=("Go back")

            select=$(printf '%s\n' "${devices_options[@]}" | dmenu -i)

            case $select in 
                "Go back")
                    menu_blue
                    ;;
                *)

                    case $select in 
                        *"(Connected) (Trusted)"*)

                            options=("Disconnect" "Untrust" "Go back")

                            further_select=$(printf '%s\n' "${options[@]}" | dmenu -i -p "$select")

                            select=$(echo $select | cut -d' ' -f1)

                            MAC_select=$(bluetoothctl devices | grep $select | cut -d' ' -f2)

                            echo $MAC_select

                            case $further_select in 
                                "Disconnect")
                                    echo "Disconnecting $select ($MAC_select) ..."
                                    bluetoothctl disconnect $MAC_select
                                    menu_blue
                                    ;;
                                "Untrust")
                                    echo "Untrusting $select ($MAC_select) ..."
                                    bluetoothctl untrust $MAC_select
                                    menu_blue
                                    ;;
                                "Go back")
                                    menu_blue
                                    ;;
                            esac
                            ;;
                        *"(Connected)"*)

                            options=("Disconnect" "Trust" "Go back")

                            further_select=$(printf '%s\n' "${options[@]}" | dmenu -i -p "$select")

                            select=$(echo $select | cut -d' ' -f1)

                            MAC_select=$(bluetoothctl devices | grep $select | cut -d' ' -f2)

                            echo $MAC_select

                            case $further_select in 
                                "Disconnect")
                                    echo "Disconnecting $select ($MAC_select) ..."
                                    bluetoothctl disconnect $MAC_select
                                    menu_blue
                                    ;;
                                "Trust")
                                    echo "Trusting $select ($MAC_select) ..."
                                    bluetoothctl trust $MAC_select
                                    menu_blue
                                    ;;
                                "Go back")
                                    menu_blue
                                    ;;
                            esac
                            ;;
                        *"(Trusted)"*)

                            options=("Connect" "Untrust" "Go back")

                            further_select=$(printf '%s\n' "${options[@]}" | dmenu -i -p "$select")

                            select=$(echo $select | cut -d' ' -f1)

                            MAC_select=$(bluetoothctl devices | grep $select | cut -d' ' -f2)

                            echo $MAC_select

                            case $further_select in 
                                "Connect")
                                    echo "Connecting $select ($MAC_select) ..."
                                    bluetoothctl connect $MAC_select
                                    menu_blue
                                    ;;
                                "Trust")
                                    echo "Untrusting $select ($MAC_select) ..."
                                    bluetoothctl untrust $MAC_select
                                    menu_blue
                                    ;;
                                "Go back")
                                    menu_blue
                                    ;;
                            esac
                            ;;
                    esac
                    
                    ;;
            esac
            ;;

        # "Connect to trusted devices")
        #
        #     trusted_devices=($(bluetoothctl devices Trusted | grep -w Device | cut -d' ' -f3))
        #
        #     devices_options=()
        #     devices_options+=(${trusted_devices[@]})
        #     devices_options+=("Go back")
        #
        #     select=$(printf '%s\n' "${devices_options[@]}" | dmenu -i)
        #
        #     case $select in 
        #         "Go back")
        #             menu_blue
        #             ;;
        #         *)
        #
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 string_to_add=$(bluetoothctl devices Trusted | grep -w ${trusted_devices[$i]} | cut -d' ' -f2)
        #                 trusted_devices[$i]+=" $string_to_add"
        #             done
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 MAC_select=$(echo ${trusted_devices[i]} | grep $select | cut -d' ' -f2)
        #
        #             done
        #
        #             echo "Trying to connect to: $MAC_select"
        #
        #             bluetoothctl connect $MAC_select
        #             ;;
        #     esac
        #     ;;
        #
        
        "Connect devices")

            duration=6

            bluetoothctl scan on &

            # Sleep for the desired duration
            sleep "$duration"

            # Stop the scan by killing the background process
            kill $(pgrep bluetoothctl)

            # Wait for the background process to finish
            wait



            available_devices=($(bluetoothctl devices | cut -d' ' -f3))
    
            # add go back option
            devices_options=()

            for (( i=0; i<${#available_devices[@]}; i++)); do

                if  bluetoothctl devices Connected | grep -w Device | grep ${available_devices[i]}; then

                    echo "${available_devices[i]} already connected!"

                else

                    if bluetoothctl devices Trusted | grep -w Device | grep ${available_devices[i]}; then

                        echo "${available_devices[i]} not connected but trusted!"

                    else

                        devices_options+=("${available_devices[i]}")
                    fi

                fi

            done

            devices_options+=("Go back")

            select=$(printf '%s\n'  "${devices_options[@]}" | dmenu -i)

            case $select in

                "Go back")
                    menu_blue
                    ;;
                *)

                    for (( i=0; i<${#available_devices[@]}; i++ )); do
                        string_to_add=$(bluetoothctl devices | grep -w ${available_devices[$i]} | cut -d' ' -f2)
                        available_devices[$i]+=" $string_to_add"
                    done


                    for (( i=0; i<${#available_devices[@]}; i++ )); do
                        MAC_select=$(echo ${available_devices[i]} | grep $select | cut -d' ' -f2)
                    done

                    echo "Trying to connect to: $MAC_select"
                    bluetoothctl connect $MAC_select
                    menu_blue
                    ;;

            esac


            ;;

        # "Disconnect devices")
        #
        #     connected_devices=($(bluetoothctl info | grep -w Name: | cut -d' ' -f2))
        #
        #     devices_options=()
        #     devices_options+=(${connected_devices[@]})
        #     devices_options+=("Go back")
        #
        #     select=$(printf '%s\n' "${devices_options[@]}" | dmenu -i)
        #
        #     case $select in 
        #
        #         "Go back")
        #             menu_blue
        #             ;;
        #         *)
        #     
        #             for (( i=0; i<${#connected_devices[@]}; i++ )); do
        #                 string_to_add=$(bluetoothctl devices Connected | grep -w ${connected_devices[$i]} | cut -d' ' -f2)
        #                 connected_devices[$i]+=" $string_to_add"
        #             done
        #
        #             for (( i=0; i<${#connected_devices[@]}; i++ )); do
        #                 MAC_select=$(echo ${connected_devices[i]} | grep $select | cut -d' ' -f2)
        #
        #             done
        #
        #             echo "Trying to disconnect from: $MAC_select"
        #
        #             bluetoothctl disconnect $MAC_select
        #             menu_blue
        #             ;;
        #     esac
        #     ;;
        #
        # "Trust devices")
        #
        #     connected_devices=($(bluetoothctl info | grep -w Name: | cut -d' ' -f2))
        #
        #
        #     devices_options=()
        #
        #     for (( i=0; i<${#connected_devices[@]}; i++)); do
        #         if  bluetoothctl devices Trusted | grep -w Device | grep ${connected_devices[i]}
        #         then
        #             echo "${connected_devices[i]} already trusted!"
        #         else
        #             devices_options+=("${connected_devices[i]}")
        #         fi
        #     done
        #
        #     devices_options+=("Go back")
        #
        #     select=$(printf '%s\n' "${devices_options[@]}" | dmenu -i)
        #     case $select in
        #         "Go back")
        #             menu_blue
        #             ;;
        #         *)
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 string_to_add=$(bluetoothctl devices Trusted | grep -w ${trusted_devices[$i]} | cut -d' ' -f2)
        #                 trusted_devices[$i]+=" $string_to_add"
        #             done
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 MAC_select=$(echo ${trusted_devices[i]} | grep $select | cut -d' ' -f2)
        #
        #             done
        #
        #             echo "Trying to trust: $MAC_select"
        #
        #             bluetoothctl trust $MAC_select
        #
        #             menu_blue
        #             ;;
        #     esac
        #
        #     ;;
        #
        # "Distrust devices")
        #
        #     trusted_devices=($(bluetoothctl devices Trusted | grep -w Device | cut -d' ' -f3))
        #
        #     devices_options=()
        #     devices_options+=(${trusted_devices[@]})
        #     devices_options+=("Go back")
        #
        #     select=$(printf '%s\n' "${devices_options[@]}" | dmenu -i)
        #
        #     case $select in 
        #         "Go back")
        #             menu_blue
        #             ;;
        #         *)
        #
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 string_to_add=$(bluetoothctl devices Trusted | grep -w ${trusted_devices[$i]} | cut -d' ' -f2)
        #                 trusted_devices[$i]+=" $string_to_add"
        #             done
        #
        #             for (( i=0; i<${#trusted_devices[@]}; i++ )); do
        #                 MAC_select=$(echo ${trusted_devices[i]} | grep $select | cut -d' ' -f2)
        #
        #             done
        #
        #             echo "Trying to untrust to: $MAC_select"
        #
        #             bluetoothctl untrust $MAC_select
        #
        #             menu_blue
        #             ;;
        #     esac
        #     ;;


        "Go back")
            # menu_main
            ;;
    esac

}

menu_blue
