#!/bin/bash

# WORK IN PROGRESS

get_devices() {
	

	default=$(pacmd list-sinks | grep '*' | awk '{ print $3 }')
        default=$((default + 1))	
	devices=$(pacmd list-sinks | grep device.description | sed 's/device.description = //' | tr -d '"' | tr -d '\t' | awk -v idx="$default" '{if (NR==idx) $1="*"$1; print}')
	selected=$(printf '%s\n' "${devices[@]}" | dmenu -i)

	echo "devices = $devices"
	echo " selected = $selected"
	echo "${#devices[@]}"
   	for i in "${!devices[@]}"; do
		echo "y"
		if [[ "${devices[$i]}" == "$selected" ]]; then
			index="$i"
			echo "yep: index: $index"
			break
       		fi
		echo "x"
	done	
	#	echo "selected: $selected"
	#echo "index: $index"


}

action_func () {
	options=("volume up" "volume down" "Mute")
	selected=$(printf '%s\n' "${options[@]}" | dmenu -i)
	case $selected in
		"volume up")
			pactl set-sink-volume 2 +30%
			;;
		"volume down")
			pactl set-sink-volume @DEFAULT_SINK@ -5%
			;;
		"Mute")
			pactl set-sink-mute @DEFAULT_SINK@ 0
			;;
	esac
}

set_default_func () {
	options=("Linkbuds" "HP-Speaker" "Asus-Speaker")

	selected=$(printf '%s\n' "${options[@]}" | dmenu -i)

	case $selected in
		"Linkbuds")
			pactl set-default-sink 2
			;;
		"HP-Speaker")
			pactl set-default-sink 1
			;;
		"Asus-Speaker")
			pactl set-default-sink 0
			;;
	esac

}

main_func () {
	options=("Output-device" "General Volume" "Application Volume")
	selected=$(printf '%s\n' "${options[@]}" | dmenu -i)

	case $selected in
		"Output-device")
			set_default_func
			main_func
			;;
		"General Volume")
			action_func	
			main_func
			;;
		"General Volume")
			
			main_func
			;;
	esac	
}
get_devices

