#!/bin/bash

# useful commands
# acpi -bi
# upower -i /org/freedesktop/UPower/devices/battery_BAT0

percent="$(cat /sys/class/power_supply/BAT0/capacity)"
status="$(cat /sys/class/power_supply/BAT0/status)"
# output="$(acpi -bi)"
output="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"

# time=$(echo "$output" | awk -F ' ' 'NR==1 {print $5}')
time_to_empty=$(echo "$output" | grep "time to empty:" | awk '{print $4}')
time_to_empty_unit=$(echo "$output" | grep "time to empty:" | awk '{print $5}')

time_to_full=$(echo "$output" | grep "time to full:" | awk '{print $4}')
time_to_full_unit=$(echo "$output" | grep "time to full:" | awk '{print $5}')


if [ "$status" == "Discharging" ]; then 
    if [ "$percent" -ge 90 ]; then
        echo "    $percent%      "
    elif [ "$percent" -ge 70 ] && [ "$percent" -lt 90 ]; then
        echo "    $percent%      "
    elif [ "$percent" -ge 40 ] && [ "$percent" -lt 70 ]; then
        echo "    $percent%      "
    elif [ "$percent" -ge 20 ] && [ "$percent" -lt 40 ]; then
        echo "    $percent%      "
    elif [ "$percent" -ge 0 ] && [ "$percent" -lt 20 ]; then
        echo "    $percent%      "
    fi
elif [ "$status" == "Full" ]; then
    echo "   100%      " 
elif [ "$status" == "Not charging" ]; then
    echo "   100%      " 
elif [ "$status" == "Charging" ]; then
    if [ "$percent" -ge 90 ]; then
        echo "    $percent%    󱐋 "
    elif [ "$percent" -ge 70 ] && [ "$percent" -lt 90 ]; then
        echo "    $percent%    󱐋 "
    elif [ "$percent" -ge 40 ] && [ "$percent" -lt 70 ]; then
        echo "    $percent%    󱐋 "
    elif [ "$percent" -ge 20 ] && [ "$percent" -lt 40 ]; then
        echo "    $percent%    󱐋 "
    elif [ "$percent" -ge 0 ] && [ "$percent" -lt 20 ]; then
        echo "    $percent%    󱐋 "
    fi
fi


if [ "$status" == "Discharging" ]; then 
    case $BUTTON in 
        1) dunstify "$time_to_empty $time_to_empty_unit";
    esac
elif [ "$status" == "Charging" ]; then
    case $BUTTON in 
        1) dunstify "$time_to_full $time_to_full_unit";
    esac
else
    case $BUTTON in
        1) dunstify "Not charging / Full"
    esac
fi
