#!/bin/bash


status_kb=$(xinput list-props 12 | grep "Device Enabled" | awk '{print $4}')
if [[ $status_kb = 1 ]]; then 
    echo "        "
elif [[ $status_kb = 0 ]]; then
    echo "    󰓶    "
fi

case $BUTTON in
    1) menu_options tablet;;
esac




