#!/bin/bash

case $BUTTON in 
    1) 
        st -e bash -c "
        sudo pacman --noconfirm -Syu && dunstify System 'Up to date!'"
        ;;
esac

updates="$(pacman -Qu | wc -l)"

if [[ ! "$updates" == "0" ]]; then
    echo "    $updates     "
fi
