#!/bin/bash

vol="$(pamixer --get-volume)"
mute=$(pamixer --get-mute)

case $BUTTON in
    1) pamixer -t && mute="$(true)";;
    3) pavucontrol;;
    4) pamixer --increase 5 && vol="$(pamixer --get-volume)";;
    5) pamixer --decrease 5 && vol="$(pamixer --get-volume)";;
    8) pavucontrol;;
esac

if [ "$mute" = true ]; then
    echo "    0% 󰖁    "
else
    echo "    $vol% 󰕾     "
fi
