#!/bin/bash

# set wallpaper
xwallpaper --zoom ~/Pictures/Wallpapers/triangle.png
cp ~/Pictures/Wallpapers/triangle.png ~/.config/wall/picture

# change dwm colors
cd ~/.config/suckless/dwm/

sed -i '3s/.*/#include "\/home\/falk\/.config\/suckless\/themes\/triangle-blue.h"/' config.h

# change st colors
cd ~/.config/suckless/st/

sed -i '3s/.*/#include "\/home\/falk\/.config\/suckless\/themes\/triangle-blue.h"/' config.h


# change dmenu colors
cd ~/.config/suckless/dmenu/

sed -i '3s/.*/#include "\/home\/falk\/.config\/suckless\/themes\/triangle-blue.h"/' config.h


st -e bash -c "
cd ~/.config/suckless/dwm/;
sudo make install;

cd ~/.config/suckless/st/;
sudo make install;

cd ~/.config/suckless/dmenu/;
sudo make install;"
