// dwm
#define DWM_BACKGROUND_COLOR "#262d37"
#define DWM_INACTIVE_BORDER_COLOR "#767b8a"
#define DWM_FONT_COLOR "#f0f2f7"
#define DWM_CURRENT_TAG_FONT_COLOR "#262d37"
#define DWM_ACTIVE_BORDER_COLOR "#f0f2f7"

// dmenu
#define DMENU_NORMAL_FG_COLOR "#f0f2f7"
#define DMENU_NORMAL_BG_COLOR "#767b8a"
#define DMENU_SELECTED_FG_COLOR "#767b8a"
#define DMENU_SELECTED_BG_COLOR "#f0f2f7"
#define DMENU_POINTER_OUTSIDE_FG_COLOR "#f0f2f7"
#define DMENU_POINTER_OUTSIDE_BG_COLOR "#767b8a"
#define DMENU_POINTER_HOVER_FG_COLOR "#f0f2f7"
#define DMENU_POINTER_HOVER_BG_COLOR "#767b8a"

// ST
#define ST_BACKGROUND_COLOR "#262d37"
#define ST_FOREGROUND_COLOR "#f0f2f7"
#define ST_BLACK_COLOR "#262d37"
#define ST_WHITE_COLOR "#f0f2f7"
#define ST_ACCENT_COLOR "#f0f2f7"
