// dwm
#define DWM_BACKGROUND_COLOR "#eff3fa"
#define DWM_INACTIVE_BORDER_COLOR "#767b8a"
#define DWM_FONT_COLOR "#2c3440"
#define DWM_CURRENT_TAG_FONT_COLOR "#eff3fa"
#define DWM_ACTIVE_BORDER_COLOR "#2c3440"

// dmenu
#define DMENU_NORMAL_FG_COLOR "#2c3440"
#define DMENU_NORMAL_BG_COLOR "#767b8a"
#define DMENU_SELECTED_FG_COLOR "#767b8a"
#define DMENU_SELECTED_BG_COLOR "#2c3440"
#define DMENU_POINTER_OUTSIDE_FG_COLOR "#2c3440"
#define DMENU_POINTER_OUTSIDE_BG_COLOR "#767b8a"
#define DMENU_POINTER_HOVER_FG_COLOR "#2c3440"
#define DMENU_POINTER_HOVER_BG_COLOR "#767b8a"

// ST
#define ST_BACKGROUND_COLOR "#767b8a"
#define ST_FOREGROUND_COLOR "#2c3440"
#define ST_BLACK_COLOR "#767b8a"
#define ST_WHITE_COLOR "#eff3fa"
#define ST_ACCENT_COLOR "#2c3440"
