// TRIANGLE 
// dwm
#define DWM_BACKGROUND_COLOR "#2e3440"
#define DWM_INACTIVE_BORDER_COLOR "#4c566a"
#define DWM_FONT_COLOR "#83a5c0"
#define DWM_CURRENT_TAG_FONT_COLOR "#2e3440"
#define DWM_ACTIVE_BORDER_COLOR "#83a5c0"

// dmenu
#define DMENU_NORMAL_FG_COLOR "#83a5c0"
#define DMENU_NORMAL_BG_COLOR "#4c566a"
#define DMENU_SELECTED_FG_COLOR "#4c566a"
#define DMENU_SELECTED_BG_COLOR "#83a5c0"
#define DMENU_POINTER_OUTSIDE_FG_COLOR "#83a5c0"
#define DMENU_POINTER_OUTSIDE_BG_COLOR "#4c566a"
#define DMENU_POINTER_HOVER_FG_COLOR "#83a5c0"
#define DMENU_POINTER_HOVER_BG_COLOR "#4c566a"

// ST
#define ST_BACKGROUND_COLOR "#2e3440"
#define ST_FOREGROUND_COLOR "#eff3fa"
#define ST_BLACK_COLOR "#2e3440"
#define ST_WHITE_COLOR "#eff3fa"
#define ST_ACCENT_COLOR "#83a5c0"
