#!/bin/bash

CONFIG_PATH=~/.config.cfg

mon_bright_type=$(grep -w MONITOR: $CONFIG_PATH | awk '{print $2}')
mon_index=($(grep -w -A4 MONITOR: $CONFIG_PATH | awk 'NR==5'))
redshift_state=$(grep -w REDSHIFT: $CONFIG_PATH | awk '{print $2}')
redshift=(1000, 1100, 1200, 1400, 1800, 2300, 3500, 6000, 10000, 15000, 25000)

light_down() {

	case $mon_bright_type in
	"ddcutil")
		case $1 in
		"max")
			for index in ${mon_index[@]}; do
				ddcutil -d $index setvcp 10 0
				wait
			done
			;;
		*)

			for index in ${mon_index[@]}; do
				ddcutil -d $index setvcp 10 - 10
				wait
			done
			;;
		esac
		;;
	"brillo")
		case $1 in
		"max")
			brillo -S 0
			;;
		*)
			brillo -U 10
			;;
		esac
		;;
	esac
}

light_up() {

	case $mon_bright_type in
	"ddcutil")
		case $1 in
		"max")
			for index in ${mon_index[@]}; do
				ddcutil -d $index setvcp 10 100
				wait
			done
			;;
		*)

			for index in ${mon_index[@]}; do
				ddcutil -d $index setvcp 10 + 10
				wait
			done
			;;
		esac
		;;
	"brillo")
		case $1 in
		"max")
			brillo -S 100
			;;
		*)
			brillo -A 10
			;;
		esac
		;;
	esac

}

red_down() {
	if [[ $1 == "max" ]]; then
		redshift_state=0
		sed -i 's/REDSHIFT: [0-9]*/REDSHIFT: '$redshift_state'/' $CONFIG_PATH
	elif [[ $redshift_state != 0 ]]; then
		redshift_state=$(($redshift_state - 1))
		sed -i 's/REDSHIFT: [0-9]*/REDSHIFT: '$redshift_state'/' $CONFIG_PATH
	fi
}

red_up() {
	if [[ $1 == "max" ]]; then
		redshift_state=9
		sed -i 's/REDSHIFT: [0-9]*/REDSHIFT: '$redshift_state'/' $CONFIG_PATH
	elif [[ $redshift_state != 9 ]]; then
		redshift_state=$(($redshift_state + 1))
		sed -i 's/REDSHIFT: [0-9]*/REDSHIFT: '$redshift_state'/' $CONFIG_PATH
	fi
}

case "$1" in

"up") light_up ;;

"down") light_down ;;

"blue")
	red_up
	redshift -P -O ${redshift[$redshift_state]}
	;;

"red")
	red_down
	redshift -P -O ${redshift[$redshift_state]}
	;;

"day")
	light_up max
	;;
"night")
	light_down max
	;;
"sea")
	red_down max
	redshift -P -O ${redshift[$redshift_state]}
	;;
"ocean")
	red_up max
	redshift -P -O ${redshift[$redshift_state]}
	;;
*) echo "unknown command" && exit 1 ;;

esac
