#!/bin/bash

vol_inc () {

    pamixer --increase 5
    pkill -RTMIN+1 dwmblocks

}

vol_dec () {

    pamixer --decrease 5
    pkill -RTMIN+1 dwmblocks

}

vol_mute () {

    pamixer -t
    pkill -RTMIN+1 dwmblocks

}


case "$1" in

	"inc") vol_inc;;

	"dec") vol_dec;;

	"mute") vol_mute;;

	*) echo "unknown command" && exit 1;;

esac
