#!/bin/bash

vol_inc() {

	pulsemixer --change-volume +5
	pkill -RTMIN+1 dwmblocks

}

vol_dec() {

	pulsemixer --change-volume -5
	pkill -RTMIN+1 dwmblocks

}

vol_mute() {

	pulsemixer --toggle-mute
	pkill -RTMIN+1 dwmblocks

}

case "$1" in

"inc") vol_inc ;;

"dec") vol_dec ;;

"mute") vol_mute ;;

*) echo "unknown command" && exit 1 ;;

esac
