#!/bin/bash

CONFIG_PATH="/var/tmp/scr_light/current_red_value"

connection_type=$(hyprctl monitors all | grep Monitor)

if [ ! -f $CONFIG_PATH ]; then
  mkdir -p $(dirname $CONFIG_PATH)
  echo "6" >$CONFIG_PATH
fi

light_down() {

  case "$1" in
  "max")
    brillo -S 0 || ddcutil -d 1 setvcp 10 0 && ddcutil -d 2 setvcp 10 0 && ddcutil -d 3 setvcp 10 0
    exit 0
    ;;
  *)
    brillo -U -10 || ddcutil -d 1 setvcp 10 - 10 && ddcutil -d 2 setvcp 10 - 10 && ddcutil -d 3 setvcp 10 - 10
    exit 0
    ;;
  esac
}

light_up() {

  case $1 in
  "max")
    brillo -S 100 || ddcutil -d 1 setvcp 10 100 && ddcutil -d 2 setvcp 10 100 && ddcutil -d 3 setvcp 10 100
    exit 0
    ;;
  *)
    brillo -A 10 || ddcutil -d 1 setvcp 10 + 10 && ddcutil -d 2 setvcp 10 + 10 && ddcutil -d 3 setvcp 10 + 10
    ;;
  esac
}

case "$1" in

"up")
  light_up
  ;;

"down")
  light_down
  ;;

"blue")
  hyprshade off
  ;;

"red")
  hyprshade on blue-light-filter
  ;;

"day")
  light_up max
  ;;
"night")
  light_down max
  ;;
*) echo "unknown command" && exit 1 ;;

esac
